### ISSUE TITLE
Windows下出现

### ISSUE THREAD

**Issue by silianpan** [carl-jin/vite-plugin-antdv1-momentjs-resolver#3]
```
TypeError: (void 0) is not a function
    at validator2 (moment-util.js:8:64)
    at assertProp (vue.runtime.esm.js:1714:10)
    at validateProp (vue.runtime.esm.js:1632:5)
    at loop (vue.runtime.esm.js:4678:17)
    at initProps (vue.runtime.esm.js:4711:33)
    at initState (vue.runtime.esm.js:4652:21)
    at VueComponent.Vue2._init (vue.runtime.esm.js:5020:5)
    at new VueComponent (vue.runtime.esm.js:5168:12)
    at createComponentInstanceForVnode (vue.runtime.esm.js:3304:10)
    at init (vue.runtime.esm.js:3133:45)
```

```
export var TimeType = {
  validator: function validator(value) {
    return typeof value === 'string' || isNil(value) || moment.isMoment(value);
  }
};
```

**Comment by annoyc** [comment]
相同问题，应该就是dev阶段未生效

**Comment by carl-jin** [comment]
已合并 PR #4
